<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChildCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $childcategories = [
            [
                'id' => 17,
                'subcategory_id' => 19,
                'name' => 'বইনামা প্রকাশন',
                'slug' => 'boinama-prokasona',
                'status' => 1,
            ],
            [
                'id' => 18,
                'subcategory_id' => 20,
                'name' => 'রাশেদুল হাসান',
                'slug' => 'rashedul-hasan',
                'status' => 1,
            ],
            [
                'id' => 19,
                'subcategory_id' => 18,
                'name' => 'ইসলামি বই',
                'slug' => 'Islamic-books',
                'status' => 1,
            ],
            [
                'id' => 22,
                'subcategory_id' => 19,
                'name' => 'ইত্যাদি গ্রন্থ প্রকাশ',
                'slug' => 'Ittadi-Grantho-Prokash',
                'status' => 1,
            ],
            [
                'id' => 23,
                'subcategory_id' => 19,
                'name' => 'ভাটিয়াল প্রকাশন',
                'slug' => 'Vatial-Prokashon',
                'status' => 1,
            ],
            [
                'id' => 24,
                'subcategory_id' => 19,
                'name' => 'অন্বেষা প্রকাশন',
                'slug' => 'annesha-prokashon',
                'status' => 1,
            ],
            [
                'id' => 25,
                'subcategory_id' => 18,
                'name' => 'অতিরিক্ত ছাড়',
                'slug' => 'extra-discount',
                'status' => 1,
            ],
            [
                'id' => 26,
                'subcategory_id' => 18,
                'name' => 'উপন্যাস',
                'slug' => 'uponnas',
                'status' => 1,
            ],
            [
                'id' => 27,
                'subcategory_id' => 18,
                'name' => 'মোটিভেশনাল ও মেডিটেশন',
                'slug' => 'Motivational-and-Meditation',
                'status' => 1,
            ],
            [
                'id' => 28,
                'subcategory_id' => 18,
                'name' => 'রাজনীতি',
                'slug' => 'Politics',
                'status' => 1,
            ],
            [
                'id' => 29,
                'subcategory_id' => 18,
                'name' => 'মুক্তিযুদ্ধ',
                'slug' => 'Liberation-War',
                'status' => 1,
            ],
            [
                'id' => 30,
                'subcategory_id' => 18,
                'name' => 'প্রি-অর্ডার',
                'slug' => 'Pre-Order',
                'status' => 1,
            ],
            [
                'id' => 31,
                'subcategory_id' => 19,
                'name' => 'শব্দশৈলী',
                'slug' => 'Shobdoshoily',
                'status' => 1,
            ],
            [
                'id' => 32,
                'subcategory_id' => 19,
                'name' => 'ছিন্নপত্র প্রকাশন',
                'slug' => 'chinnapatra-prokashon',
                'status' => 1,
            ],
            [
                'id' => 33,
                'subcategory_id' => 19,
                'name' => 'শিশুরাজ্য প্রকাশন',
                'slug' => 'shishurajya-prokashon',
                'status' => 1,
            ],
            [
                'id' => 34,
                'subcategory_id' => 19,
                'name' => 'রাইয়ান প্রকাশন',
                'slug' => 'Rayan-prokashon',
                'status' => 1,
            ],
            [
                'id' => 35,
                'subcategory_id' => 19,
                'name' => 'সমকালীন প্রকাশন',
                'slug' => 'Somokalin-Prokashon',
                'status' => 1,
            ],
            [
                'id' => 36,
                'subcategory_id' => 19,
                'name' => 'নবপ্রকাশ',
                'slug' => 'Nobo-Prokash',
                'status' => 1,
            ],
            [
                'id' => 37,
                'subcategory_id' => 19,
                'name' => 'নতুন বিন্যাস প্রকাশ‌ন',
                'slug' => 'Natun-Binnas',
                'status' => 1,
            ],
            [
                'id' => 38,
                'subcategory_id' => 19,
                'name' => 'মাকতাবাতুল হাসান',
                'slug' => 'Maktabatul-Hasan',
                'status' => 1,
            ],
            [
                'id' => 39,
                'subcategory_id' => 19,
                'name' => 'স্বরবর্ণ প্রকাশন',
                'slug' => 'Shorborno-prokashon',
                'status' => 1,
            ],
            [
                'id' => 40,
                'subcategory_id' => 19,
                'name' => 'গার্ডিয়ান পাবলিকেশন্স',
                'slug' => 'Guardian-Publication',
                'status' => 1,
            ],
            [
                'id' => 41,
                'subcategory_id' => 19,
                'name' => 'সন্দীপন প্রকাশন',
                'slug' => 'Sondipon-Prokashon',
                'status' => 1,
            ],
            [
                'id' => 42,
                'subcategory_id' => 19,
                'name' => 'আয়ান প্রকাশন',
                'slug' => 'Ayan-Prokashon',
                'status' => 1,
            ],
            [
                'id' => 43,
                'subcategory_id' => 19,
                'name' => 'রাহনুমা প্রকাশনী',
                'slug' => 'Rahnuma-Prokashani',
                'status' => 1,
            ],
            [
                'id' => 44,
                'subcategory_id' => 19,
                'name' => 'ভাষাচিত্র',
                'slug' => 'Bhashachitra',
                'status' => 1,
            ],
            [
                'id' => 45,
                'subcategory_id' => 19,
                'name' => 'জলধি',
                'slug' => 'Jolodhi',
                'status' => 1,
            ],
            [
                'id' => 46,
                'subcategory_id' => 19,
                'name' => 'ফ্যালকন পাবলিকেশন',
                'slug' => 'Falcon-Publication',
                'status' => 1,
            ],
            [
                'id' => 47,
                'subcategory_id' => 19,
                'name' => 'প্রচ্ছদ প্রকাশন',
                'slug' => 'prossod-prokashon',
                'status' => 1,
            ],
            [
                'id' => 48,
                'subcategory_id' => 19,
                'name' => 'সাহিত‌্যদেশ',
                'slug' => 'Sahityodesh',
                'status' => 1,
            ],
            [
                'id' => 49,
                'subcategory_id' => 19,
                'name' => 'সিয়ান পাবলিকেশন',
                'slug' => 'Sean-Publication',
                'status' => 1,
            ],
            [
                'id' => 50,
                'subcategory_id' => 19,
                'name' => 'প্রিয়মুখ',
                'slug' => 'Priyomokh',
                'status' => 1,
            ],
            [
                'id' => 51,
                'subcategory_id' => 19,
                'name' => 'কালান্তর প্রকাশনী',
                'slug' => 'Kalantor-Prokasoni',
                'status' => 1,
            ],
            [
                'id' => 52,
                'subcategory_id' => 19,
                'name' => 'ঝিঙেফুল পাবলিকেশন',
                'slug' => 'Jhingephul-Publication',
                'status' => 1,
            ],
            [
                'id' => 53,
                'subcategory_id' => 19,
                'name' => 'বাংলা সাহিত্য',
                'slug' => 'Bangla-Sahityo',
                'status' => 1,
            ],
            [
                'id' => 54,
                'subcategory_id' => 19,
                'name' => 'আন্দালিব প্রকাশনী',
                'slug' => 'Andalib-Prokashoni',
                'status' => 1,
            ],
            [
                'id' => 55,
                'subcategory_id' => 19,
                'name' => 'বাংলা বই সংগ্রহ',
                'slug' => 'Bangla-Boi-Shongroho',
                'status' => 1,
            ],
            [
                'id' => 56,
                'subcategory_id' => 19,
                'name' => 'পুরুষ',
                'slug' => 'Purush',
                'status' => 1,
            ],
            [
                'id' => 57,
                'subcategory_id' => 19,
                'name' => 'পত্রিকা ও বিজ্ঞাপন',
                'slug' => 'Patrica-and-Advertisement',
                'status' => 1,
            ],
            [
                'id' => 58,
                'subcategory_id' => 19,
                'name' => 'মহাকাব্য',
                'slug' => 'Maha-Kabbo',
                'status' => 1,
            ],
            [
                'id' => 59,
                'subcategory_id' => 19,
                'name' => 'বাংলা গল্প',
                'slug' => 'Bangla-Golpo',
                'status' => 1,
            ],
            [
                'id' => 60,
                'subcategory_id' => 19,
                'name' => 'অমিতান্ত প্রকাশনী',
                'slug' => 'Amitanth-Publishing',
                'status' => 1,
            ],
            [
                'id' => 61,
                'subcategory_id' => 19,
                'name' => 'বই পাঠশালা',
                'slug' => 'Boi-Pathshala',
                'status' => 1,
            ],
            [
                'id' => 62,
                'subcategory_id' => 19,
                'name' => 'দ্রুত বই',
                'slug' => 'Druto-Boi',
                'status' => 1,
            ],
            [
                'id' => 63,
                'subcategory_id' => 19,
                'name' => 'আলেম সাহিত্য',
                'slug' => 'Aleem-Sahityo',
                'status' => 1,
            ],
            [
                'id' => 64,
                'subcategory_id' => 19,
                'name' => 'ইংরেজি ভাষার বই',
                'slug' => 'English-Books',
                'status' => 1,
            ]];

        DB::table('childcategories')->insert($childcategories);
    }
}
